const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={view:'home',theme:localStorage.getItem('norte-theme')||'dark',step:+(localStorage.getItem('norte-step')||0),answers:JSON.parse(localStorage.getItem('norte-answers')||'{}'),route:+(localStorage.getItem('norte-route')||0)};
const questions=[
['business','O que você quer abrir?','Conta pra gente do seu jeito. Pode escrever como você falaria com alguém.','text','Ex.: Quero abrir uma barbearia com meu irmão','Aqui a Norte só quer entender sua ideia. Depois ela traduz isso para os termos oficiais.'],
['partners','Você vai tocar esse negócio sozinho ou com alguém?','Escolha a opção que mais parece com sua situação agora.','options',['Sozinho','Com sócio','Ainda não sei'],'Isso ajuda a entender como a empresa pode ser organizada.'],
['place','Onde esse negócio vai funcionar?','Pode ser em casa, numa loja, só pela internet ou indo até o cliente.','options',['Na minha casa','Loja ou sala','Só pela internet','Na casa do cliente','Outro lugar'],'O local pode mudar regras e licenças.'],
['city','Em qual cidade vai ser?','Cada cidade pode ter regras diferentes.','text','Ex.: Rio de Janeiro - RJ','A cidade ajuda a identificar quais regras locais precisam ser verificadas.'],
['address','Você já sabe o endereço?','Se ainda estiver procurando, tudo bem.','options',['Sim','Ainda estou procurando'],'Depois a Norte ajuda a verificar se sua atividade pode funcionar nesse endereço.'],
['activity','O que você vai fazer nesse negócio?','Escolha uma opção simples.','options',['Vender produtos','Prestar serviços','Os dois'],'Por trás disso existe a atividade oficial da empresa, chamada CNAE.'],
['revenue','Quanto você acha que vai entrar de dinheiro por mês?','É só uma estimativa. Se não souber, tudo bem.','options',['Até R$ 5 mil','R$ 5 mil a R$ 20 mil','Mais de R$ 20 mil','Não faço ideia'],'Essa estimativa ajuda no planejamento e no enquadramento inicial.'],
['employees','Vai ter funcionário logo no começo?','Se ainda não decidiu, marque “Ainda não sei”.','options',['Sim','Não','Ainda não sei'],'Ter funcionário pode mudar obrigações e custos.'],
['name','Você já pensou num nome pra empresa?','Pode ser o nome que gostaria de usar.','text','Ex.: Norte Barbearia','A disponibilidade do nome é verificada depois.'],
['simple','Sobre os impostos: você já sabe se quer usar o Simples Nacional?','Se isso parecer complicado, escolha “Quero entender primeiro”.','options',['Sim','Quero entender primeiro','Não sei'],'O Simples Nacional é um sistema próprio para pequenas empresas que cumprem as regras.']
];
const routeSteps=['Entender sua atividade','Ver se o endereço pode ser usado','Organizar a empresa','Registro e CNPJ','Simples Nacional','Licenças necessárias'];
function save(){localStorage.setItem('norte-theme',state.theme);localStorage.setItem('norte-step',state.step);localStorage.setItem('norte-answers',JSON.stringify(state.answers));localStorage.setItem('norte-route',state.route)}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),1600)}
function home(){return `<section class="hero"><div class="eyebrow">Norte • abrir empresa sem burocratês</div><h1>Abra sua empresa.<br><span class="gradient">Sem se perder no caminho.</span></h1><p class="lead">Você conta o que quer fazer do seu jeito. A Norte organiza o caminho, traduz os termos difíceis e mostra o próximo passo.</p><svg class="route-art" viewBox="0 0 760 120"><path d="M20 86 C150 12,250 115,390 50 S610 18,740 76" fill="none" stroke="var(--line)" stroke-width="2"/><path class="run" d="M20 86 C150 12,250 115,390 50 S610 18,740 76" fill="none" stroke-width="3"/></svg><div class="row"><button class="btn primary" id="start">Quero abrir minha empresa</button><button class="btn secondary" data-go="route">Ver como funciona</button></div><p class="muted" style="font-size:12px">Você não precisa entender de CNAE, natureza jurídica ou imposto para começar.</p></section><div class="grid grid2" style="margin-top:14px"><article class="card"><div class="eyebrow">Como a Norte fala</div><h3>Português de gente normal.</h3><p class="muted">A burocracia fica por trás. Na frente, perguntas simples.</p></article><article class="card"><div class="eyebrow">Sua rota</div><h3>${Math.round(state.route/6*100)}% organizada</h3><div class="progress"><i style="width:${state.route/6*100}%"></i></div></article></div>`}
function route(){return `<section class="card"><div class="eyebrow">Sua rota</div><h2>Um passo de cada vez.</h2><p class="muted">Você sabe o que vem agora e o que pode esperar.</p></section><div class="route-list">${routeSteps.map((s,i)=>`<article class="route-step ${i===state.route?'current':i>state.route?'locked':''}"><b>${i<state.route?'✓':i+1}</b><div class="eyebrow">${i<state.route?'Concluído':i===state.route?'Agora':'Depois'}</div><h3>${s}</h3>${i===state.route&&state.route<6?'<button class="btn primary" id="advance">Entendi essa etapa</button>':''}</article>`).join('')}</div>`}
function tools(){return `<section class="card"><div class="eyebrow">Ferramentas</div><h2>Contas sem susto.</h2><p class="muted">Projeções simples de faturamento, custos e planejamento vão entrar aqui.</p></section>`}
function company(){return `<section class="card"><div class="eyebrow">Minha Empresa</div><h2>${state.answers.business||'Seu negócio começa aqui.'}</h2><p class="muted">${state.answers.city||'Faça o diagnóstico inicial para montar seu painel.'}</p></section>`}
function help(){return `<section class="card"><div class="eyebrow">Ajuda</div><h2>Não entendeu? Pergunta do seu jeito.</h2><p class="muted">A Norte explica primeiro em linguagem simples e mostra o termo oficial só quando ele ajudar.</p></section>`}
function render(){const v=$('#view');v.innerHTML=state.view==='home'?home():state.view==='route'?route():state.view==='tools'?tools():state.view==='company'?company():help();$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));if($('#start'))$('#start').onclick=openWizard;if($('#advance'))$('#advance').onclick=()=>{state.route=Math.min(6,state.route+1);save();render()}}
function nav(v){state.view=v;$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();scrollTo({top:0,behavior:'smooth'})}
function openWizard(){state.step=Math.min(state.step,questions.length-1);$('#wizard').classList.remove('hidden');document.body.style.overflow='hidden';drawQuestion()}
function closeWizard(){$('#wizard').classList.add('hidden');document.body.style.overflow='';save()}
function drawQuestion(){if(state.step>=questions.length)return summary();const q=questions[state.step],pct=Math.round((state.step+1)/questions.length*100);$('#stepText').textContent=`${state.step+1} de ${questions.length}`;$('#pct').textContent=pct+'%';$('#bar').style.width=pct+'%';let input=q[3]==='text'?`<input id="input" class="biginput" value="${state.answers[q[0]]||''}" placeholder="${q[4]}"><button id="next" class="next">Continuar</button>`:`<div class="answers">${q[4].map(o=>`<button class="answer" data-answer="${o}"><span>${o}</span><span>→</span></button>`).join('')}</div>`;$('#question').innerHTML=`<div class="qcard"><div class="qtag">Passo ${state.step+1}</div><h2>${q[1]}</h2><p>${q[2]}</p>${input}<div class="helpers"><button id="voice">● Falar em vez de digitar</button><button id="explainBtn">Me explica essa pergunta</button></div><div id="explain" class="explain">${q[5]}</div></div>`;$$('[data-answer]').forEach(b=>b.onclick=()=>{state.answers[q[0]]=b.dataset.answer;state.step++;save();drawQuestion()});if($('#next'))$('#next').onclick=()=>{const val=$('#input').value.trim();if(!val)return toast('Escreve uma resposta pra continuar.');state.answers[q[0]]=val;state.step++;save();drawQuestion()};$('#explainBtn').onclick=()=>{$('#explain').style.display=$('#explain').style.display==='block'?'none':'block'};$('#voice').onclick=()=>toast('Microfone entra na próxima versão.')}
function summary(){const a=state.answers;$('#stepText').textContent='Pronto';$('#pct').textContent='100%';$('#bar').style.width='100%';$('#question').innerHTML=`<div class="qcard"><div class="qtag">Diagnóstico inicial</div><h2>Pronto. Já entendemos o começo do seu negócio.</h2><p>Agora a Norte transforma isso numa rota simples.</p><div class="summary"><div><span>Negócio</span><strong>${a.business||'—'}</strong></div><div><span>Com quem</span><strong>${a.partners||'—'}</strong></div><div><span>Onde</span><strong>${a.place||'—'}</strong></div><div><span>Cidade</span><strong>${a.city||'—'}</strong></div><div><span>Simples</span><strong>${a.simple||'—'}</strong></div></div><button id="build" class="next">Montar minha rota</button></div>`;$('#build').onclick=()=>{state.route=0;save();closeWizard();nav('route');toast('Sua rota foi montada.')}} 
document.body.classList.toggle('dark',state.theme==='dark');$('#theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',state.theme==='dark');save()};$$('[data-view]').forEach(b=>b.onclick=()=>nav(b.dataset.view));$('#close').onclick=closeWizard;render();